name: Daily TikTok Scraper

on:
  schedule:
    - cron: "0 */12 * * *"  # runs every 12 hours
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install playwright

      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps

      - name: Run scraper
        run: node main.mjs
