name: TikTok Daily Report

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: npm install playwright axios
      - name: Run script
        run: node main.mjs
        env:
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          MIN_VIEWS: 50
          LOOKBACK_HOURS: 48
