name: Run TikTok Bot

on:
  schedule:
    - cron: "0 */8 * * *" # every 8 hours
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install node-fetch@2
      - run: node main.mjs
