name: TikTok Daily Report

on:
  schedule:
    - cron: "0 9 * * *"   # daily at 09:00 UTC (change as you wish)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i playwright axios

      # Install the Chromium binary + Linux deps for Playwright
      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps chromium
          npx playwright install-deps chromium

      - name: Run scraper
        env:
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_BOT_TOKEN:  ${{ secrets.DISCORD_BOT_TOKEN }}
          MIN_VIEWS: "50"
          LOOKBACK_HOURS: "48"
        run: node main.mjs
