name: TikTok Daily Report

on:
  schedule:
    - cron: "0 9 * * *"        # daily at 09:00 UTC (change if you want)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15        # hard cap the whole job
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i playwright axios

      # Install full Chrome & required libs (helps with blocking)
      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps chrome
          npx playwright install-deps chrome

      - name: Run scraper
        env:
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_BOT_TOKEN:  ${{ secrets.DISCORD_BOT_TOKEN }}
          MIN_VIEWS: "50"
          LOOKBACK_HOURS: "48"
        run: node main.mjs
